CREATE DATABASE MARKET

USE MARKET

CREATE TABLE PRODUCTS(Id int, Name nvarchar(50), Price Decimal(10, 2))

ALTER TABLE PRODUCTS ADD Brand nvarchar(50)

INSERT INTO PRODUCTS (Id, Name, Price, Brand)
values 
(1, 'X5', 10000, 'BMW'),
(2, 'X6', 15000, 'BMW'),
(3, '525', 40000, 'BMW')

SELECT Id, Name, Price, Brand FROM PRODUCTS WHERE PRICE < (SELECT AVG(PRICE) FROM PRODUCTS)

SELECT Id, Name, Price, Brand FROM PRODUCTS WHERE PRICE > 10000

SELECT (BRAND + ' ' + NAME) AS ProductInfo FROM PRODUCTS WHERE LEN(BRAND) > 5 